# AST2050 (G3) FRU EEPROM smoke test.
# SPDX-License-Identifier: Apache-2.0
# EEPROM_AT24 auto-enables (default y) because the devicetree has an okay
# "atmel,at24" node; it drives the I2C engine via I2C_ASPEED_G3.
CONFIG_EEPROM=y
