# AST2050 (G3) watchdog TIMEOUT-INTERRUPT smoke (#189).
# SPDX-License-Identifier: Apache-2.0
# WDT_ASPEED_G3 auto-enables (default y) from the okay "aspeed,ast2050-wdt" DT
# node. CONFIG_WDT_MULTISTAGE is NOT needed: the G3 WDT is one-stage (interrupt
# OR reset), mapped as WDT_FLAG_RESET_NONE + callback -> WDT_INTR (VIC-27).
CONFIG_WATCHDOG=y
