/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: all_slot_power_off
 * Address:  0x0002f2fc
 * Size:     272 bytes
 *
 * Auto-generated by Ghidra default
 */


void all_slot_power_off(void)

{
  short sVar1;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  
  local_20 = 0;
  local_1c = 0;
  local_18 = 0;
  local_14 = 0;
  printf(DAT_0002f40c);
  local_1c = DAT_0002f410;
  local_20 = DAT_0002f414;
  local_14 = 0x430f3;
  sVar1 = _lx_QueueSend(DAT_0002f418,&local_20,0);
  if (sVar1 != 0) {
    printf(DAT_0002f41c);
  }
  local_1c = DAT_0002f420;
  local_20 = DAT_0002f424;
  local_14 = 0x80f0;
  sVar1 = _lx_QueueSend(DAT_0002f418,&local_20,0);
  if (sVar1 != 0) {
    printf(DAT_0002f41c);
  }
  return;
}

