/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: all_slot_power_off_reg
 * Address:  0x0002f188
 * Size:     360 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4
all_slot_power_off_reg(undefined param_1,undefined param_2,undefined param_3,undefined4 param_4)

{
  undefined local_1c;
  undefined local_1b;
  byte local_1a;
  byte local_19;
  undefined4 local_18;
  undefined local_13;
  undefined local_12;
  undefined local_11;
  
  local_1b = 0x30;
  local_1c = 0;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  for (local_19 = 0; local_19 < 2; local_19 = local_19 + 1) {
    for (local_1a = 0; local_1a < 8; local_1a = local_1a + 1) {
      get_PEX8696_addr_port(local_19 * '\b' + local_1a,&local_1b,&local_1c);
      *DAT_0002f2f0 = local_1c;
      DAT_0002f2f0[1] = 0x3c;
      DAT_0002f2f0[2] = 0x20;
      read_pex8696_register(local_11,local_1b,4,local_18);
      memcpy(DAT_0002f2f4,DAT_0002f2f8,4);
      DAT_0002f2f0[5] = DAT_0002f2f0[5] | 3;
      DAT_0002f2f0[5] = DAT_0002f2f0[5] | 4;
      write_pex8696_register(local_11,local_1b,3,local_18);
    }
  }
  return 0;
}

