/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: dump_PEX8696_reg
 * Address:  0x00037a98
 * Size:     192 bytes
 *
 * Auto-generated by Ghidra default
 */


void dump_PEX8696_reg(void)

{
  short sVar1;
  void *local_20;
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  
  local_20 = (void *)0x0;
  local_1c = 0;
  local_18 = 0;
  local_14 = 0;
  printf(DAT_00037b58);
  memset(DAT_00037b5c,0,8);
  local_1c = DAT_00037b60;
  local_20 = DAT_00037b5c;
  local_14 = 0x430f3;
  sVar1 = _lx_QueueSend(DAT_00037b64,&local_20,0);
  if (sVar1 != 0) {
    printf(DAT_00037b68);
  }
  return;
}

