/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: get_PEX8696_addr_port
 * Address:  0x00037f7c
 * Size:     352 bytes
 *
 * Auto-generated by Ghidra default
 */


void get_PEX8696_addr_port(int param_1)

{
  byte local_36;
  byte local_35;
  undefined auStack_34 [16];
  undefined auStack_24 [16];
  int local_14;
  
  local_14 = param_1;
  memcpy(auStack_24,DAT_000380dc,0x10);
  memcpy(auStack_34,DAT_000380e0,0x10);
  *DAT_000380e4 = 0;
  for (local_35 = 0; local_35 < 2; local_35 = local_35 + 1) {
    for (local_36 = 0; local_36 < 8; local_36 = local_36 + 1) {
      if (((int)(uint)*(byte *)((uint)local_35 + local_14) >> local_36 & 1U) != 0) {
        *(undefined *)(DAT_000380e8 + (uint)*DAT_000380e4) =
             auStack_24[(uint)local_36 + (uint)local_35 * 8];
        *(undefined *)(DAT_000380ec + (uint)*DAT_000380e4) =
             auStack_34[(uint)local_36 + (uint)local_35 * 8];
        *DAT_000380e4 = *DAT_000380e4 + 1;
      }
    }
  }
  return;
}

