/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: get_PEX8696_addr_port
 * Address:  0x0002e66c
 * Size:     160 bytes
 *
 * Auto-generated by Ghidra default
 */


void get_PEX8696_addr_port(byte param_1,undefined *param_2,undefined *param_3)

{
  undefined auStack_3c [16];
  undefined auStack_2c [16];
  undefined *local_1c;
  undefined *local_18;
  byte local_11;
  
  local_1c = param_3;
  local_18 = param_2;
  local_11 = param_1;
  memcpy(auStack_2c,DAT_0002e70c,0x10);
  memcpy(auStack_3c,DAT_0002e710,0x10);
  *local_18 = auStack_2c[local_11];
  *local_1c = auStack_3c[local_11];
  return;
}

