/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: get_PEX8696_addr_port
 * Address:  0x000317e4
 * Size:     312 bytes
 *
 * Auto-generated by Ghidra default
 */


void get_PEX8696_addr_port(void)

{
  byte local_32;
  byte local_31;
  undefined auStack_30 [16];
  undefined auStack_20 [16];
  
  memcpy(auStack_20,DAT_0003191c,0x10);
  memcpy(auStack_30,DAT_00031920,0x10);
  for (local_31 = 0; local_31 < 2; local_31 = local_31 + 1) {
    for (local_32 = 0; local_32 < 8; local_32 = local_32 + 1) {
      if (((int)(uint)*(byte *)(DAT_00031924 + (uint)local_31) >> local_32 & 1U) != 0) {
        *DAT_00031928 = auStack_20[(uint)local_32 + (uint)local_31 * 8];
        *DAT_0003192c = auStack_30[(uint)local_32 + (uint)local_31 * 8];
        OEM_GPU_Init_Clear((uint)local_31 * 8 + (uint)local_32);
      }
    }
  }
  return;
}

