/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: gpu_power_on_2_6_10_14
 * Address:  0x00030420
 * Size:     136 bytes
 *
 * Auto-generated by Ghidra default
 */


void gpu_power_on_2_6_10_14(void)

{
  undefined local_18;
  undefined local_17;
  undefined auStack_14 [4];
  
  memcpy(auStack_14,DAT_000304a8,2);
  local_18 = 0;
  local_17 = 0;
  printf(DAT_000304ac);
  gpu_un_protect(0x33);
  pex8696_un_protect(auStack_14);
  filter_on_gpu(auStack_14,&local_18);
  pex8696_slot_power_on(&local_18);
  gpu_power_attention_pulse(&local_18);
  return;
}

