/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: multi_host_mode_set
 * Address:  0x00038230
 * Size:     312 bytes
 *
 * Auto-generated by Ghidra default
 */


void multi_host_mode_set(ushort param_1)

{
  byte local_16;
  byte local_15;
  undefined2 local_14;
  ushort local_12;
  
  local_14 = 0;
  local_15 = 0;
  if (param_1 == 0x802e) {
    local_16 = 0x32;
  }
  else {
    if (param_1 < 0x802f) {
      if (param_1 == 0x802d) {
        local_16 = 0x30;
        goto LAB_00038304;
      }
    }
    else if (param_1 == 0x802f) {
      local_16 = 0x34;
      goto LAB_00038304;
    }
    local_16 = 0x36;
  }
LAB_00038304:
  local_12 = param_1;
  RawIOIdxTblGetIdx(param_1,0xf,&local_14);
  RawDiscreteRead(local_14,0,0,&local_15);
  printf(DAT_00038368,(uint)local_16,(uint)local_15);
  return;
}

