/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_hp_ctrl
 * Address:  0x00031454
 * Size:     228 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_hp_ctrl(char param_1)

{
  undefined local_13;
  undefined local_12;
  
  for (local_12 = 0; local_12 < 2; local_12 = local_12 + 1) {
    for (local_13 = 0; local_13 < 8; local_13 = local_13 + 1) {
      if (((int)(uint)*(byte *)(DAT_00031538 + (uint)local_12) >> local_13 & 1U) != 0) {
        if (param_1 == '\x01') {
          pex8696_hp_off(local_12 * '\b' + local_13);
        }
        else {
          pex8696_hp_on(local_12 * '\b' + local_13);
        }
      }
    }
  }
  return;
}

