/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_un_protect_reg
 * Address:  0x0002fc74
 * Size:     372 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4
pex8696_un_protect_reg(undefined param_1,undefined param_2,undefined param_3,undefined4 param_4)

{
  undefined local_1c;
  undefined local_1b;
  byte local_1a;
  byte local_19;
  undefined4 local_18;
  undefined local_13;
  undefined local_12;
  undefined local_11;
  
  local_1b = 0x30;
  local_1c = 0;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  for (local_19 = 0; local_19 < 2; local_19 = local_19 + 1) {
    for (local_1a = 0; local_1a < 8; local_1a = local_1a + 1) {
      if (((int)(uint)*(byte *)(DAT_0002fde8 + (uint)local_19) >> local_1a & 1U) != 0) {
        get_PEX8696_addr_port(local_19 * '\b' + local_1a,&local_1b,&local_1c);
        *DAT_0002fdec = local_1c;
        DAT_0002fdec[1] = 0x3c;
        DAT_0002fdec[2] = 0x1f;
        read_pex8696_register(local_11,local_1b,4,local_18);
        memcpy(DAT_0002fdf0,DAT_0002fdf4,4);
        DAT_0002fdec[6] = DAT_0002fdec[6] & 0xfb;
        write_pex8696_register(local_11,local_1b,3,local_18);
      }
    }
  }
  return 0;
}

