/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_slot_power_on
 * Address:  0x0002fa90
 * Size:     440 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_slot_power_on(byte *param_1)

{
  short sVar1;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  byte *local_14;
  
  local_24 = 0;
  local_20 = 0;
  local_1c = 0;
  local_18 = 0;
  local_14 = param_1;
  printf(DAT_0002fc48,(uint)*param_1,(uint)param_1[1]);
  *DAT_0002fc4c = *local_14;
  DAT_0002fc4c[1] = local_14[1];
  local_20 = DAT_0002fc50;
  local_24 = DAT_0002fc54;
  local_18 = 0x430f3;
  sVar1 = _lx_QueueSend(DAT_0002fc58,&local_24,0);
  if (sVar1 != 0) {
    printf(DAT_0002fc5c);
  }
  local_20 = DAT_0002fc60;
  local_24 = DAT_0002fc64;
  local_18 = 0x80f0;
  sVar1 = _lx_QueueSend(DAT_0002fc58,&local_24,0);
  if (sVar1 != 0) {
    printf(DAT_0002fc5c);
  }
  local_20 = DAT_0002fc68;
  local_24 = DAT_0002fc6c;
  local_18 = 0x5cf4;
  sVar1 = _lx_QueueSend(DAT_0002fc58,&local_24,0);
  if (sVar1 != 0) {
    printf(DAT_0002fc70);
  }
  return;
}

