/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_multi_host_mode_reg_set
 * Address:  0x00037420
 * Size:     388 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_multi_host_mode_reg_set(undefined param_1,char param_2)

{
  uint uVar1;
  undefined4 uVar2;
  undefined *local_44;
  undefined4 local_40;
  undefined4 local_3c;
  undefined4 local_38;
  undefined auStack_34 [8];
  undefined local_2c;
  undefined local_2b;
  undefined auStack_2a [6];
  undefined local_24;
  undefined local_23;
  undefined auStack_22 [6];
  undefined local_1c;
  undefined local_1b;
  undefined auStack_1a [8];
  char local_12;
  undefined local_11;
  
  local_12 = param_2;
  local_11 = param_1;
  memcpy(&local_1c,DAT_000375a4,8);
  memcpy(&local_24,DAT_000375a8,8);
  memcpy(&local_2c,DAT_000375ac,8);
  memcpy(auStack_34,DAT_000375ac,8);
  local_3c = 0;
  if (local_12 != '\x01') {
    local_40 = DAT_000375b0;
    local_38._0_2_ = CONCAT11(local_24,0xf3);
    local_38._0_3_ = CONCAT12(local_23,(undefined2)local_38);
    local_44 = auStack_22;
    local_38 = (uint)(uint3)local_38;
    _lx_QueueSend(DAT_000375b4,&local_44,0);
    uVar1 = local_38;
    local_38._0_2_ = CONCAT11(local_2c,(undefined)local_38);
    local_38._3_1_ = SUB41(uVar1,3);
    local_38._0_3_ = CONCAT12(local_2b,(undefined2)local_38);
    local_44 = auStack_2a;
    _lx_QueueSend(DAT_000375b4,&local_44,0);
    uVar2 = local_38;
    local_38._0_2_ = CONCAT11(local_1c,(undefined)local_38);
    local_38._3_1_ = SUB41(uVar2,3);
    local_38._0_3_ = CONCAT12(local_1b,(undefined2)local_38);
    local_44 = auStack_1a;
    _lx_QueueSend(DAT_000375b4,&local_44,0);
  }
  return;
}

