/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_hp_on
 * Address:  0x00031184
 * Size:     232 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_hp_on(undefined param_1)

{
  switch(param_1) {
  case 0:
    system(DAT_000312ac);
    break;
  case 1:
    system(DAT_000312b0);
    break;
  case 2:
    system(DAT_000312b4);
    break;
  case 3:
    system(DAT_000312b8);
    break;
  case 4:
    system(DAT_000312bc);
    break;
  case 5:
    system(DAT_000312c0);
    break;
  case 6:
    system(DAT_000312c4);
    break;
  case 7:
    system(DAT_000312c8);
    break;
  case 8:
    system(DAT_000312cc);
    break;
  case 9:
    system(DAT_000312d0);
    break;
  case 10:
    system(DAT_000312d4);
    break;
  case 0xb:
    system(DAT_000312d8);
    break;
  case 0xc:
    system(DAT_000312dc);
    break;
  case 0xd:
    system(DAT_000312e0);
    break;
  case 0xe:
    system(DAT_000312e4);
    break;
  case 0xf:
    system(DAT_000312e8);
  }
  return;
}

