/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_all_slot_off
 * Address:  0x000375b8
 * Size:     288 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4 pex8696_all_slot_off(undefined param_1,byte param_2,undefined param_3,undefined4 param_4)

{
  undefined auStack_2c [11];
  byte local_21;
  undefined auStack_20 [7];
  byte local_19;
  undefined4 local_18;
  undefined local_13;
  byte local_12;
  undefined local_11;
  
  local_19 = 0x30;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  memcpy(auStack_20,DAT_000376d8,4);
  local_21 = 0;
  memcpy(auStack_2c,DAT_000376dc,6);
  for (local_19 = local_12; local_19 < 0x38; local_19 = local_19 + 2) {
    for (local_21 = 0; local_21 < 4; local_21 = local_21 + 1) {
      *DAT_000376e0 = auStack_20[local_21];
      memcpy(DAT_000376e4,auStack_2c,6);
      write_pex8696_register(local_11,local_19,local_13,local_18);
    }
  }
  return 0;
}

