/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_slot_power_ctrl
 * Address:  0x000332ac
 * Size:     676 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4
pex8696_slot_power_ctrl(undefined param_1,undefined param_2,undefined param_3,undefined4 param_4)

{
  undefined2 local_1a;
  undefined4 local_18;
  undefined local_13;
  undefined local_12;
  undefined local_11;
  
  local_1a = 0;
  *DAT_00033550 = *DAT_00033554;
  DAT_00033550[1] = 0x3c;
  DAT_00033550[2] = 0x20;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  memcpy(DAT_00033558,DAT_0003355c,4);
  if (*DAT_00033560 == '\x01') {
    printf(DAT_00033564);
    DAT_00033550[5] = DAT_00033550[5] | 3;
    DAT_00033550[5] = DAT_00033550[5] | 4;
  }
  else {
    printf(DAT_00033568);
    DAT_00033550[5] = DAT_00033550[5] & 0xfc;
    DAT_00033550[5] = DAT_00033550[5] | 1;
    DAT_00033550[5] = DAT_00033550[5] & 0xfb;
    write_pex8696_register(local_11,local_12,local_13,local_18);
    DAT_00033550[1] = 0x3c;
    DAT_00033550[2] = 0x8d;
    read_pex8696_register(local_11,local_12,4,local_18);
    memcpy(DAT_00033558,DAT_0003355c,4);
    DAT_00033550[4] = DAT_00033550[4] | 1;
    write_pex8696_register(local_11,local_12,3,local_18);
    _lx_ThreadSleep(10);
    DAT_00033550[4] = DAT_00033550[4] & 0xfe;
    write_pex8696_register(local_11,local_12,local_13,local_18);
    DAT_00033550[1] = 0x3c;
    DAT_00033550[2] = 0x8a;
    read_pex8696_register(local_11,local_12,4,local_18);
    memcpy(DAT_00033558,DAT_0003355c,4);
    DAT_00033550[6] = DAT_00033550[6] | 0x20;
    pex8696_hp_ctrl(1);
  }
  write_pex8696_register(local_11,local_12,local_13,local_18);
  memset(DAT_0003356c,0,2);
  RawIOIdxTblGetIdx(0x800c,0x18,&local_1a);
  RawIRQEnable(local_1a);
  *DAT_00033570 = 0;
  return 0;
}

