/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8647_cfg_multi_host_8
 * Address:  0x00036dbc
 * Size:     296 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4
pex8647_cfg_multi_host_8(undefined param_1,undefined param_2,undefined param_3,undefined4 param_4)

{
  undefined auStack_30 [12];
  undefined auStack_24 [11];
  byte local_19;
  undefined4 local_18;
  undefined local_13;
  undefined local_12;
  undefined local_11;
  
  local_19 = 0;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  memcpy(auStack_30,DAT_00036ee4,0x12);
  *DAT_00036ee8 = 4;
  memcpy(DAT_00036eec,auStack_24,6);
  write_pex8647_register(local_11,local_12,local_13,local_18);
  *DAT_00036ee8 = 0;
  for (local_19 = 0; local_19 < 2; local_19 = local_19 + 1) {
    memcpy(DAT_00036eec,auStack_30 + (uint)local_19 * 6,6);
    write_pex8647_register(local_11,local_12,local_13,local_18);
    _lx_ThreadSleep(0x14);
  }
  return 0;
}

