/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_cfg_multi_host_4
 * Address:  0x00036cd4
 * Size:     220 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4
pex8696_cfg_multi_host_4(undefined param_1,undefined param_2,undefined param_3,undefined4 param_4)

{
  undefined auStack_28 [15];
  byte local_19;
  undefined4 local_18;
  undefined local_13;
  undefined local_12;
  undefined local_11;
  
  local_19 = 0;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  memcpy(auStack_28,DAT_00036db0,0xc);
  *DAT_00036db4 = 0;
  for (local_19 = 0; local_19 < 2; local_19 = local_19 + 1) {
    memcpy(DAT_00036db8,auStack_28 + (uint)local_19 * 6,6);
    write_pex8696_register(local_11,local_12,local_13,local_18);
  }
  return 0;
}

