/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_un_protect
 * Address:  0x0002fdf8
 * Size:     248 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_un_protect(byte *param_1)

{
  short sVar1;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  byte *local_14;
  
  local_24 = 0;
  local_20 = 0;
  local_1c = 0;
  local_18 = 0;
  local_14 = param_1;
  printf(DAT_0002fef0,(uint)*param_1,(uint)param_1[1]);
  *DAT_0002fef4 = *local_14;
  DAT_0002fef4[1] = local_14[1];
  local_20 = DAT_0002fef8;
  local_24 = DAT_0002fefc;
  local_18 = 0x430f3;
  sVar1 = _lx_QueueSend(DAT_0002ff00,&local_24,0);
  if (sVar1 != 0) {
    printf(DAT_0002ff04);
  }
  return;
}

