/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8647_multi_host_mode_cfg
 * Address:  0x00037944
 * Size:     312 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8647_multi_host_mode_cfg(void)

{
  char cVar1;
  short sVar2;
  void *local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  byte local_11;
  
  local_11 = 0;
  printf(DAT_00037a80,(uint)*DAT_00037a7c);
  for (local_11 = 0; local_11 < 4; local_11 = local_11 + 2) {
    local_24 = (void *)0x0;
    local_20 = 0;
    local_1c = 0;
    local_18 = 0;
    memset(DAT_00037a84,0,8);
    cVar1 = is_cfg_multi_host_8(local_11);
    if (cVar1 == '\x01') {
      local_20 = DAT_00037a88;
    }
    else {
      local_20 = DAT_00037a8c;
    }
    if (local_11 == 0) {
      local_18._0_2_ = 0xd4f3;
    }
    else {
      local_18._0_2_ = 0xd0f3;
    }
    local_24 = DAT_00037a84;
    local_18 = (uint)CONCAT12(3,(undefined2)local_18);
    sVar2 = _lx_QueueSend(DAT_00037a90,&local_24,0);
    if (sVar2 != 0) {
      printf(DAT_00037a94);
    }
  }
  return;
}

