/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_all_slot_power_off
 * Address:  0x0003836c
 * Size:     192 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_all_slot_power_off(void)

{
  short sVar1;
  void *local_20;
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  
  local_20 = (void *)0x0;
  local_1c = 0;
  local_18 = 0;
  local_14 = 0;
  printf(DAT_0003842c);
  memset(DAT_00038430,0,8);
  local_1c = DAT_00038434;
  local_20 = DAT_00038430;
  local_14 = 0x330f3;
  sVar1 = _lx_QueueSend(DAT_00038438,&local_20,0);
  if (sVar1 != 0) {
    printf(DAT_0003843c);
  }
  return;
}

