/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_hp_off
 * Address:  0x000312ec
 * Size:     232 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_hp_off(undefined param_1)

{
  switch(param_1) {
  case 0:
    system(DAT_00031414);
    break;
  case 1:
    system(DAT_00031418);
    break;
  case 2:
    system(DAT_0003141c);
    break;
  case 3:
    system(DAT_00031420);
    break;
  case 4:
    system(DAT_00031424);
    break;
  case 5:
    system(DAT_00031428);
    break;
  case 6:
    system(DAT_0003142c);
    break;
  case 7:
    system(DAT_00031430);
    break;
  case 8:
    system(DAT_00031434);
    break;
  case 9:
    system(DAT_00031438);
    break;
  case 10:
    system(DAT_0003143c);
    break;
  case 0xb:
    system(DAT_00031440);
    break;
  case 0xc:
    system(DAT_00031444);
    break;
  case 0xd:
    system(DAT_00031448);
    break;
  case 0xe:
    system(DAT_0003144c);
    break;
  case 0xf:
    system(DAT_00031450);
  }
  return;
}

