/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_dump
 * Address:  0x000371b8
 * Size:     240 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4 pex8696_dump(undefined param_1,undefined param_2,undefined param_3,undefined4 param_4)

{
  ushort uVar1;
  undefined4 local_1c;
  
  for (local_1c = 0; uVar1 = local_1c._2_2_, local_1c._2_2_ < 0x1000;
      local_1c = ((local_1c >> 0x10) + 4) * 0x10000) {
    *(byte *)(DAT_000372a8 + 1) = (local_1c._2_1_ >> 6) + 0x3c;
    *(char *)(DAT_000372a8 + 2) = (char)(uVar1 >> 2);
    read_pex8696_register(param_1,param_2,param_3,param_4);
  }
  return 0;
}

