/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_multi_host_mode_cfg
 * Address:  0x00037768
 * Size:     448 bytes
 *
 * Auto-generated by Ghidra default
 */


void pex8696_multi_host_mode_cfg(void)

{
  char cVar1;
  short sVar2;
  void *local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  byte local_11;
  
  local_11 = 0;
  printf(DAT_0003792c,(uint)*DAT_00037928,(uint)DAT_00037928[1],(uint)DAT_00037928[2],
         (uint)DAT_00037928[3]);
  local_11 = 0;
  do {
    if (3 < local_11) {
      return;
    }
    local_24 = (void *)0x0;
    local_20 = 0;
    local_1c = 0;
    local_18 = 0;
    memset(DAT_00037930,0,8);
    if ((DAT_00037928[local_11] == 0) || (cVar1 = is_cfg_multi_host_8(local_11), cVar1 == '\x01')) {
      local_20 = DAT_00037934;
    }
    else {
      local_20 = DAT_00037938;
    }
    if (local_11 == 1) {
      local_18._0_2_ = 0x34f3;
    }
    else if (local_11 < 2) {
      if (local_11 == 0) {
        local_18._0_2_ = 0x30f3;
      }
      else {
LAB_000378c0:
        local_18._0_2_ = 0x36f3;
      }
    }
    else {
      if (local_11 != 2) goto LAB_000378c0;
      local_18._0_2_ = 0x32f3;
    }
    local_24 = DAT_00037930;
    local_18 = (uint)CONCAT12(3,(undefined2)local_18);
    sVar2 = _lx_QueueSend(DAT_0003793c,&local_24,0);
    if (sVar2 != 0) {
      printf(DAT_00037940);
    }
    local_11 = local_11 + 1;
  } while( true );
}

