/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: pex8696_cfg
 * Address:  0x000372ac
 * Size:     356 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4 pex8696_cfg(undefined param_1,byte param_2,undefined param_3,undefined4 param_4)

{
  undefined auStack_48 [34];
  byte local_26;
  byte local_25;
  undefined auStack_24 [11];
  byte local_19;
  undefined4 local_18;
  undefined local_13;
  byte local_12;
  undefined local_11;
  
  local_19 = 0x30;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  memcpy(auStack_24,DAT_00037410,6);
  local_25 = 0;
  local_26 = 0;
  memcpy(auStack_48,DAT_00037414,0x1e);
  for (local_19 = local_12; local_19 < 0x38; local_19 = local_19 + 2) {
    for (local_25 = 0; local_25 < 6; local_25 = local_25 + 1) {
      *DAT_00037418 = auStack_24[local_25];
      for (local_26 = 0; local_26 < 5; local_26 = local_26 + 1) {
        memcpy(DAT_0003741c,auStack_48 + (uint)local_26 * 6,6);
        write_pex8696_register(local_11,local_19,local_13,local_18);
      }
    }
  }
  return 0;
}

