/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: PI2CWriteRead
 * Address:  0x000253c4
 * Size:     760 bytes
 *
 * Auto-generated by Ghidra default
 */


int PI2CWriteRead(byte param_1,undefined param_2,undefined param_3,undefined4 param_4,
                 undefined param_5,undefined4 param_6,char param_7)

{
  short sVar1;
  int iVar2;
  int local_34;
  undefined4 local_30;
  undefined4 local_2c;
  byte local_28;
  undefined local_27;
  byte local_26;
  undefined local_25;
  undefined local_24;
  char local_23;
  int local_20;
  char local_1c;
  byte local_1b;
  char local_1a;
  undefined local_19;
  undefined4 local_18;
  undefined local_13;
  undefined local_12;
  byte local_11;
  
  local_19 = param_5;
  local_1a = param_7;
  local_1b = param_1 & 0xf;
  local_1c = (char)((int)(param_1 & 0xf0) >> 4);
  if (6 < local_1b) {
    return 1;
  }
  local_20 = (uint)local_1b * 0x34 + DAT_000256bc;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  if (*(char *)(local_20 + 0x24) == '\0') {
    PI2CInitialize(param_1,0);
  }
  if (*(char *)(local_20 + 0x24) == '\x01') {
    sVar1 = _lx_SemaphoreGet(local_20 + 0x10,0x14);
    if (sVar1 != 0) {
      return 2;
    }
    if (((local_1a != '\x01') && (local_1c != '\x0f')) &&
       (iVar2 = I2CMuxHandler(local_11,0), iVar2 != 0)) {
      I2CMuxHandler(local_11,1);
      _lx_SemaphorePut(local_20 + 0x10);
      return iVar2;
    }
    local_28 = local_1b;
    local_27 = local_12;
    local_30 = local_18;
    local_25 = local_13;
    local_2c = param_6;
    local_24 = local_19;
    local_26 = 0;
    local_23 = local_1a;
    iVar2 = ioctl(*DAT_000256c0,0xc010b702,&local_30);
    if (iVar2 != 0) {
      _lx_SemaphorePut(local_20 + 0x10);
      return 1;
    }
    if ((local_1a != '\x01') && (local_1c != '\x0f')) {
      I2CMuxHandler(local_11,1);
    }
    _lx_SemaphorePut(local_20 + 0x10);
  }
  if (local_26 == 1) {
    local_34 = 3;
  }
  else {
    if (local_26 < 2) {
      if (local_26 == 0) {
        local_34 = 0;
        goto LAB_00025684;
      }
    }
    else if (local_26 == 2) {
      local_34 = 4;
      goto LAB_00025684;
    }
    local_34 = 1;
  }
LAB_00025684:
  if ((*(char *)(local_20 + 0x21) == '\0') && (local_34 != 0)) {
    local_34 = 1;
  }
  return local_34;
}

