/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: PI2CMuxWriteRead
 * Address:  0x000256c4
 * Size:     264 bytes
 *
 * Auto-generated by Ghidra default
 */


undefined4
PI2CMuxWriteRead(byte param_1,undefined param_2,undefined param_3,undefined4 param_4,
                undefined param_5,undefined4 param_6,undefined param_7)

{
  int iVar1;
  undefined4 local_34;
  undefined4 local_30;
  undefined4 local_2c;
  byte local_28;
  undefined local_27;
  char local_26;
  undefined local_25;
  undefined local_24;
  undefined local_23;
  undefined4 local_20;
  undefined local_1c;
  byte local_1b;
  undefined local_1a;
  undefined local_19;
  undefined4 local_18;
  undefined local_13;
  undefined local_12;
  byte local_11;
  
  local_24 = param_5;
  local_23 = param_7;
  local_1c = 0xf;
  local_20 = 0;
  local_28 = param_1 & 0xf;
  local_2c = param_6;
  local_26 = '\0';
  local_30 = param_4;
  local_27 = param_2;
  local_25 = param_3;
  local_1b = local_28;
  local_1a = local_23;
  local_19 = local_24;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  iVar1 = ioctl(*DAT_000257cc,0xc010b702,&local_30);
  if (iVar1 == 0) {
    if (local_26 == '\0') {
      local_34 = 0;
    }
    else {
      local_34 = 1;
    }
  }
  else {
    local_34 = 1;
  }
  return local_34;
}

