/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: read_pex8647_register
 * Address:  0x00036998
 * Size:     296 bytes
 *
 * Auto-generated by Ghidra default
 */


bool read_pex8647_register(undefined param_1,byte param_2,byte param_3,void *param_4)

{
  int iVar1;
  undefined4 local_1c;
  void *local_18;
  byte local_13;
  byte local_12;
  undefined local_11;
  
  local_1c = (uint)param_3;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  memcpy((void *)((int)&local_1c + 1),param_4,3);
  printf(DAT_00036ac0,(uint)local_12,local_1c & 0xff,local_1c >> 8 & 0xff,local_1c >> 0x10 & 0xff,
         local_1c >> 0x18);
  iVar1 = PI2CWriteRead(local_11,local_12,4,&local_1c,4,&local_1c,0);
  if (iVar1 == 0) {
    printf(DAT_00036ac8,local_1c & 0xff,local_1c >> 8 & 0xff,local_1c >> 0x10 & 0xff,
           local_1c >> 0x18);
    memcpy(DAT_00036acc,&local_1c,2);
  }
  else {
    printf(DAT_00036ac4);
  }
  return iVar1 != 0;
}

