/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: read_plx_eeprom
 * Address:  0x000dd6cc
 * Size:     268 bytes
 *
 * Auto-generated by Ghidra default
 */


void read_plx_eeprom(byte param_1,byte param_2,ushort param_3)

{
  undefined *puVar1;
  undefined uVar2;
  short sVar3;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  ushort local_14;
  undefined2 uStack_12;
  
  _local_14 = CONCAT22(CONCAT11(param_1,param_2),param_3);
  local_24 = 0;
  local_20 = 0;
  local_1c = 0;
  local_18 = 0;
  printf(DAT_000dd7d8,(uint)param_1,(uint)param_2,(uint)param_3);
  puVar1 = DAT_000dd7dc;
  *DAT_000dd7dc = (char)_local_14;
  puVar1[1] = (char)((uint)_local_14 >> 8);
  local_20 = DAT_000dd7e0;
  local_18 = CONCAT31(local_18._1_3_,0xf3);
  uVar2 = find_slave_addr(uStack_12._1_1_,(undefined)uStack_12);
  local_24 = DAT_000dd7e4;
  local_18 = (uint)CONCAT12(4,CONCAT11(uVar2,(undefined)local_18));
  sVar3 = _lx_QueueSend(DAT_000dd7e8,&local_24,0);
  if (sVar3 != 0) {
    printf(DAT_000dd7ec);
  }
  return;
}

