/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: Start_GPU_Power_Sequence
 * Address:  0x00033ae8
 * Size:     184 bytes
 *
 * Auto-generated by Ghidra default
 */


void Start_GPU_Power_Sequence(undefined param_1,undefined4 param_2)

{
  int iVar1;
  undefined2 local_1a;
  undefined4 local_18;
  undefined local_11;
  
  local_1a = 0;
  local_18 = param_2;
  local_11 = param_1;
  printf(DAT_00033ba0);
  RawIOIdxTblGetIdx(0x800c,0x18,&local_1a);
  RawIRQDisable(local_1a);
  RawIRQClear(local_1a);
  iVar1 = PSU_PGOOD();
  if (iVar1 == 1) {
    *DAT_00033ba4 = 1;
  }
  else {
    RawIRQEnable(local_1a);
  }
  return;
}

