/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: write_pex8696_register
 * Address:  0x0002ead4
 * Size:     276 bytes
 *
 * Auto-generated by Ghidra default
 */


bool write_pex8696_register(undefined param_1,byte param_2,byte param_3,void *param_4)

{
  int iVar1;
  undefined4 local_20;
  uint local_1c;
  void *local_18;
  byte local_13;
  byte local_12;
  undefined local_11;
  
  local_1c = 0;
  local_20 = (uint)param_3;
  local_18 = param_4;
  local_13 = param_3;
  local_12 = param_2;
  local_11 = param_1;
  memcpy((void *)((int)&local_20 + 1),param_4,7);
  printf(DAT_0002ebe8,(uint)local_12,local_20 & 0xff,local_20 >> 8 & 0xff,local_20 >> 0x10 & 0xff,
         local_20 >> 0x18,local_1c & 0xff,local_1c >> 8 & 0xff,local_1c >> 0x10 & 0xff,
         local_1c >> 0x18);
  iVar1 = PI2CWriteRead(local_11,local_12,8,&local_20,0,0,0);
  if (iVar1 != 0) {
    printf(DAT_0002ebec);
  }
  return iVar1 != 0;
}

