/* Decompiled from Dell C410X BMC firmware (fullfw)
 * Function: write_plx_eeprom
 * Address:  0x000dd7f0
 * Size:     364 bytes
 *
 * Auto-generated by Ghidra default
 */


void write_plx_eeprom(byte param_1,byte param_2,ushort param_3,byte *param_4)

{
  undefined *puVar1;
  undefined uVar2;
  short sVar3;
  undefined4 local_28;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  byte *local_18;
  ushort local_14;
  undefined2 uStack_12;
  
  _local_14 = CONCAT22(CONCAT11(param_1,param_2),param_3);
  local_28 = 0;
  local_24 = 0;
  local_20 = 0;
  local_1c = 0;
  local_18 = param_4;
  printf(DAT_000dd95c,(uint)param_1,(uint)param_2,(uint)param_3,(uint)*param_4,(uint)param_4[1],
         (uint)param_4[2],(uint)param_4[3]);
  memcpy(DAT_000dd960,local_18,4);
  puVar1 = DAT_000dd964;
  *DAT_000dd964 = (char)_local_14;
  puVar1[1] = (char)((uint)_local_14 >> 8);
  local_24 = DAT_000dd968;
  local_1c = CONCAT31(local_1c._1_3_,0xf3);
  uVar2 = find_slave_addr(uStack_12._1_1_,(undefined)uStack_12);
  local_28 = DAT_000dd96c;
  local_1c = (uint)CONCAT12(3,CONCAT11(uVar2,(undefined)local_1c));
  sVar3 = _lx_QueueSend(DAT_000dd970,&local_28,0);
  if (sVar3 != 0) {
    printf(DAT_000dd974);
  }
  return;
}

