SUMMARY = "Populate the KGPE-D16 motherboard FRU inventory in QEMU (no EEPROM)"
DESCRIPTION = "Ships a standard IPMI FRU binary for the ASUS KGPE-D16 motherboard \
and a oneshot service that loads it into the D-Bus inventory via \
phosphor-read-eeprom (fruid 0x56 = /system/chassis/motherboard). This makes \
`ipmitool fru print` return real board identity when the faithful kgpe-d16-bmc \
QEMU machine has no emulated I2C FRU EEPROM. The blob is generated by \
recipes/ipmi/gen_fru.py (IPMI Platform Management FRU Information Storage v1.0)."
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta/files/common-licenses/Apache-2.0;md5=89aea4e17d99a7cacdbeed46a0096b10"
PR = "r1"

inherit allarch
inherit obmc-phosphor-systemd

SRC_URI = " \
    file://motherboard-fru.bin \
    file://kgpe-d16-fru-populate.service \
    "
S = "${UNPACKDIR}"

# phosphor-read-eeprom lives in phosphor-ipmi-fru; the object is hosted by the
# inventory manager.
RDEPENDS:${PN} += "phosphor-ipmi-fru"

SYSTEMD_SERVICE:${PN} = "kgpe-d16-fru-populate.service"

do_install() {
    install -d ${D}${datadir}/kgpe-d16
    install -m 0644 ${UNPACKDIR}/motherboard-fru.bin \
        ${D}${datadir}/kgpe-d16/motherboard-fru.bin
}

FILES:${PN} += "${datadir}/kgpe-d16/motherboard-fru.bin"
